-- GERADO POR gerar_itens.py — não edite à mão.
-- Fontes: data/scripts/actions/items/potions.lua, data/scripts/spells/
-- conjuring/ e data/items/items.xml do próprio servidor.
-- tipo da potion: hp, mp, ambos ou outro (outro = não serve para auto-heal)
ItensServidor = {
  potions = {
    { id = 7642, nome = "great spirit potion", tipo = "ambos", level = 80 },
    { id = 23374, nome = "ultimate spirit potion", tipo = "ambos", level = 130 },
    { id = 266, nome = "health potion", tipo = "hp", level = 0 },
    { id = 7876, nome = "small health potion", tipo = "hp", level = 0 },
    { id = 236, nome = "strong health potion", tipo = "hp", level = 50 },
    { id = 239, nome = "great health potion", tipo = "hp", level = 80 },
    { id = 7643, nome = "ultimate health potion", tipo = "hp", level = 130 },
    { id = 23375, nome = "supreme health potion", tipo = "hp", level = 200 },
    { id = 268, nome = "mana potion", tipo = "mp", level = 0 },
    { id = 237, nome = "strong mana potion", tipo = "mp", level = 50 },
    { id = 238, nome = "great mana potion", tipo = "mp", level = 80 },
    { id = 23373, nome = "ultimate mana potion", tipo = "mp", level = 130 },
    { id = 6558, nome = "flask of demonic blood", tipo = "outro", level = 0 },
    { id = 7439, nome = "berserk potion", tipo = "outro", level = 0 },
    { id = 7440, nome = "mastermind potion", tipo = "outro", level = 0 },
    { id = 7443, nome = "bullseye potion", tipo = "outro", level = 0 },
    { id = 7644, nome = "antidote potion", tipo = "outro", level = 0 },
    { id = 49271, nome = "transcendence potion", tipo = "outro", level = 0 },
    { id = 35563, nome = "magic shield potion", tipo = "outro", level = 14 },
  },
  runas = {
    { id = 3203, nome = "animate dead rune", magia = "adana mort" },
    { id = 3161, nome = "avalanche rune", magia = "adori mas frigo" },
    { id = 3147, nome = "blank rune", magia = "adori blank" },
    { id = 3178, nome = "chameleon rune", magia = "adevo ina" },
    { id = 3177, nome = "convince creature rune", magia = "adeta sio" },
    { id = 3153, nome = "cure poison rune", magia = "adana pox" },
    { id = 3148, nome = "destroy field rune", magia = "adito grav" },
    { id = 3197, nome = "disintegrate rune", magia = "adito tera" },
    { id = 3149, nome = "energy bomb rune", magia = "adevo mas vis" },
    { id = 3164, nome = "energy field rune", magia = "adevo grav vis" },
    { id = 3166, nome = "energy wall rune", magia = "adevo mas grav vis" },
    { id = 3200, nome = "explosion rune", magia = "adevo mas hur" },
    { id = 3192, nome = "fire bomb rune", magia = "adevo mas flam" },
    { id = 3188, nome = "fire field rune", magia = "adevo grav flam" },
    { id = 3190, nome = "fire wall rune", magia = "adevo mas grav flam" },
    { id = 3189, nome = "fireball rune", magia = "adori flam" },
    { id = 3191, nome = "great fireball rune", magia = "adori mas flam" },
    { id = 3198, nome = "heavy magic missile rune", magia = "adori vis" },
    { id = 3182, nome = "holy missile rune", magia = "adori san" },
    { id = 3158, nome = "icicle rune", magia = "adori frigo" },
    { id = 3152, nome = "intense healing rune", magia = "adura gran" },
    { id = 3174, nome = "light magic missile rune", magia = "adori min vis" },
    { id = 21351, nome = "light stone shower rune", magia = "adori infir mas tera" },
    { id = 21352, nome = "lightest missile rune", magia = "adori infir vis" },
    { id = 3180, nome = "magic wall rune", magia = "adevo grav tera" },
    { id = 3165, nome = "paralyse rune", magia = "adana ani" },
    { id = 3173, nome = "poison bomb rune", magia = "adevo mas pox" },
    { id = 3172, nome = "poison field rune", magia = "adevo grav pox" },
    { id = 3176, nome = "poison wall rune", magia = "adevo mas grav pox" },
    { id = 3195, nome = "soulfire rune", magia = "adevo res flam" },
    { id = 3179, nome = "stalagmite rune", magia = "adori tera" },
    { id = 3175, nome = "stone shower rune", magia = "adori mas tera" },
    { id = 3155, nome = "sudden death rune", magia = "adori gran mort" },
    { id = 3202, nome = "thunderstorm rune", magia = "adori mas vis" },
    { id = 3160, nome = "ultimate healing rune", magia = "adura vita" },
    { id = 3156, nome = "wild growth rune", magia = "adevo grav vita" },
  },
}
