-- GERADO POR gerar_spells.py — não edite à mão.
-- Fonte: data/scripts/spells/ do próprio servidor.
-- grupo: 1 = ataque, 2 = cura, 3 = suporte
SpellsServidor = {
  { nome = "Spiritual Outburst", palavras = "exori gran mas nia", grupo = 1, level = 0, mana = 425, vocacoes = { "monk", "exalted monk" } },
  { nome = "Swift Jab", palavras = "exori infir pug", grupo = 1, level = 0, mana = 3, vocacoes = { "monk", "exalted monk" } },
  { nome = "Tiger Clash", palavras = "exori infir nia", grupo = 1, level = 0, mana = 3, vocacoes = { "monk", "exalted monk" } },
  { nome = "Buzz", palavras = "exori infir vis", grupo = 1, level = 1, mana = 6, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Chill Out", palavras = "exevo infir frigo hur", grupo = 1, level = 1, mana = 8, vocacoes = { "druid", "elder druid" } },
  { nome = "Lesser Ethereal Spear", palavras = "exori infir con", grupo = 1, level = 1, mana = 6, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Lesser Front Sweep", palavras = "exori infir min", grupo = 1, level = 1, mana = 6, vocacoes = { "knight", "elite knight" } },
  { nome = "Mud Attack", palavras = "exori infir tera", grupo = 1, level = 1, mana = 6, vocacoes = { "druid", "elder druid" } },
  { nome = "Practise Fire Wave", palavras = "exevo dis flam hur", grupo = 1, level = 1, mana = 5, vocacoes = { "none" } },
  { nome = "Scorch", palavras = "exevo infir flam hur", grupo = 1, level = 1, mana = 8, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Apprentice's Strike", palavras = "exori min flam", grupo = 1, level = 8, mana = 6, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Energy Strike", palavras = "exori vis", grupo = 1, level = 12, mana = 20, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Terra Strike", palavras = "exori tera", grupo = 1, level = 13, mana = 20, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Double Jab", palavras = "exori pug", grupo = 1, level = 14, mana = 30, vocacoes = { "monk", "exalted monk" } },
  { nome = "Flame Strike", palavras = "exori flam", grupo = 1, level = 14, mana = 20, vocacoes = { "sorcerer", "druid", "master sorcerer", "elder druid" } },
  { nome = "Ice Strike", palavras = "exori frigo", grupo = 1, level = 15, mana = 20, vocacoes = { "druid", "sorcerer", "elder druid", "master sorcerer" } },
  { nome = "Brutal Strike", palavras = "exori ico", grupo = 1, level = 16, mana = 30, vocacoes = { "knight", "elite knight" } },
  { nome = "Death Strike", palavras = "exori mort", grupo = 1, level = 16, mana = 20, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Physical Strike", palavras = "exori moe ico", grupo = 1, level = 16, mana = 20, vocacoes = { "druid", "elder druid" } },
  { nome = "Fire Wave", palavras = "exevo flam hur", grupo = 1, level = 18, mana = 25, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Greater Tiger Clash", palavras = "exori nia", grupo = 1, level = 18, mana = 50, vocacoes = { "monk", "exalted monk" } },
  { nome = "Ice Wave", palavras = "exevo frigo hur", grupo = 1, level = 18, mana = 25, vocacoes = { "druid", "elder druid" } },
  { nome = "Energy Beam", palavras = "exevo vis lux", grupo = 1, level = 23, mana = 40, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Ethereal Spear", palavras = "exori con", grupo = 1, level = 23, mana = 25, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Ignite", palavras = "utori flam", grupo = 1, level = 26, mana = 30, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Whirlwind Throw", palavras = "exori hur", grupo = 1, level = 28, mana = 40, vocacoes = { "knight", "elite knight" } },
  { nome = "Great Energy Beam", palavras = "exevo gran vis lux", grupo = 1, level = 29, mana = 110, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Mystic Repulse", palavras = "exori amp pug", grupo = 1, level = 30, mana = 150, vocacoes = { "monk", "exalted monk" } },
  { nome = "Groundshaker", palavras = "exori mas", grupo = 1, level = 33, mana = 160, vocacoes = { "knight", "elite knight" } },
  { nome = "Electrify", palavras = "utori vis", grupo = 1, level = 34, mana = 30, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Berserk", palavras = "exori", grupo = 1, level = 35, mana = 115, vocacoes = { "knight", "elite knight" } },
  { nome = "Flurry of Blows", palavras = "exori mas pug", grupo = 1, level = 35, mana = 110, vocacoes = { "monk", "exalted monk" } },
  { nome = "Energy Wave", palavras = "exevo vis hur", grupo = 1, level = 38, mana = 170, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Great Fire Wave", palavras = "exevo gran flam hur", grupo = 1, level = 38, mana = 120, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Terra Wave", palavras = "exevo tera hur", grupo = 1, level = 38, mana = 170, vocacoes = { "druid", "elder druid" } },
  { nome = "Divine Missile", palavras = "exori san", grupo = 1, level = 40, mana = 20, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Inflict Wound", palavras = "utori kor", grupo = 1, level = 40, mana = 30, vocacoes = { "knight", "elite knight", "monk", "exalted monk" } },
  { nome = "Strong Ice Wave", palavras = "exevo gran frigo hur", grupo = 1, level = 40, mana = 170, vocacoes = { "druid", "elder druid" } },
  { nome = "Divine Caldera", palavras = "exevo mas san", grupo = 1, level = 50, mana = 160, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Envenom", palavras = "utori pox", grupo = 1, level = 50, mana = 30, vocacoes = { "druid", "elder druid" } },
  { nome = "Lightning", palavras = "exori amp vis", grupo = 1, level = 55, mana = 60, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Rage of the Skies", palavras = "exevo gran mas vis", grupo = 1, level = 55, mana = 600, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Wrath of Nature", palavras = "exevo gran mas tera", grupo = 1, level = 55, mana = 700, vocacoes = { "druid", "elder druid" } },
  { nome = "Eternal Winter", palavras = "exevo gran mas frigo", grupo = 1, level = 60, mana = 1050, vocacoes = { "druid", "elder druid" } },
  { nome = "Hell's Core", palavras = "exevo gran mas flam", grupo = 1, level = 60, mana = 1100, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Sweeping Takedown", palavras = "exori mas nia", grupo = 1, level = 60, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Chained Penance", palavras = "exori med pug", grupo = 1, level = 70, mana = 180, vocacoes = { "monk", "exalted monk" } },
  { nome = "Front Sweep", palavras = "exori min", grupo = 1, level = 70, mana = 200, vocacoes = { "knight", "elite knight" } },
  { nome = "Holy Flash", palavras = "utori san", grupo = 1, level = 70, mana = 30, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Strong Flame Strike", palavras = "exori gran flam", grupo = 1, level = 70, mana = 60, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Strong Terra Strike", palavras = "exori gran tera", grupo = 1, level = 70, mana = 60, vocacoes = { "druid", "elder druid" } },
  { nome = "Curse", palavras = "utori mort", grupo = 1, level = 75, mana = 30, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Strong Energy Strike", palavras = "exori gran vis", grupo = 1, level = 80, mana = 60, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Strong Ice Strike", palavras = "exori gran frigo", grupo = 1, level = 80, mana = 60, vocacoes = { "druid", "elder druid" } },
  { nome = "Fierce Berserk", palavras = "exori gran", grupo = 1, level = 90, mana = 340, vocacoes = { "knight", "elite knight" } },
  { nome = "Greater Flurry of Blows", palavras = "exori gran mas pug", grupo = 1, level = 90, mana = 300, vocacoes = { "monk", "exalted monk" } },
  { nome = "Strong Ethereal Spear", palavras = "exori gran con", grupo = 1, level = 90, mana = 55, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Ultimate Flame Strike", palavras = "exori max flam", grupo = 1, level = 90, mana = 100, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Ultimate Terra Strike", palavras = "exori max tera", grupo = 1, level = 90, mana = 100, vocacoes = { "druid", "elder druid" } },
  { nome = "Ultimate Energy Strike", palavras = "exori max vis", grupo = 1, level = 100, mana = 100, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Ultimate Ice Strike", palavras = "exori max frigo", grupo = 1, level = 100, mana = 100, vocacoes = { "druid", "elder druid" } },
  { nome = "Annihilation", palavras = "exori gran ico", grupo = 1, level = 110, mana = 300, vocacoes = { "knight", "elite knight" } },
  { nome = "Forceful Uppercut", palavras = "exori gran pug", grupo = 1, level = 110, mana = 325, vocacoes = { "monk", "exalted monk" } },
  { nome = "Devastating Knockout", palavras = "exori gran nia", grupo = 1, level = 125, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Divine Grenade", palavras = "exevo tempo mas san", grupo = 1, level = 300, mana = 160, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Executioner's Throw", palavras = "exori amp kor", grupo = 1, level = 300, mana = 225, vocacoes = { "knight", "elite knight" } },
  { nome = "Great Death Beam", palavras = "exevo max mort", grupo = 1, level = 300, mana = 140, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Ice Burst", palavras = "exevo ulus frigo", grupo = 1, level = 300, mana = 230, vocacoes = { "druid", "elder druid" } },
  { nome = "Terra Burst", palavras = "exevo ulus tera", grupo = 1, level = 300, mana = 230, vocacoes = { "druid", "elder druid" } },
  { nome = "Bruise Bane", palavras = "exura infir ico", grupo = 2, level = 1, mana = 10, vocacoes = { "knight", "elite knight" } },
  { nome = "Magic Patch", palavras = "exura infir", grupo = 2, level = 1, mana = 6, vocacoes = { "druid", "elder druid", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Practise Healing", palavras = "exura dis", grupo = 2, level = 1, mana = 5, vocacoes = { "none" } },
  { nome = "Light Healing", palavras = "exura", grupo = 2, level = 8, mana = 20, vocacoes = { "druid", "elder druid", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Wound Cleansing", palavras = "exura ico", grupo = 2, level = 8, mana = 40, vocacoes = { "knight", "elite knight" } },
  { nome = "Cure Poison", palavras = "exana pox", grupo = 2, level = 10, mana = 30, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Heal Friend", palavras = "exura sio", grupo = 2, level = 18, mana = 120, vocacoes = { "druid", "elder druid" } },
  { nome = "Restore Balance", palavras = "exura tio sio", grupo = 2, level = 18, mana = 120, vocacoes = { "monk", "exalted monk" } },
  { nome = "Intense Healing", palavras = "exura gran", grupo = 2, level = 20, mana = 70, vocacoes = { "druid", "elder druid", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Cure Electrification", palavras = "exana vis", grupo = 2, level = 22, mana = 30, vocacoes = { "druid", "elder druid" } },
  { nome = "Cure Burning", palavras = "exana flam", grupo = 2, level = 30, mana = 30, vocacoes = { "druid", "elder druid" } },
  { nome = "Ultimate Healing", palavras = "exura vita", grupo = 2, level = 30, mana = 160, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Divine Healing", palavras = "exura san", grupo = 2, level = 35, mana = 160, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Mass Healing", palavras = "exura gran mas res", grupo = 2, level = 36, mana = 150, vocacoes = { "druid", "elder druid" } },
  { nome = "Cure Bleeding", palavras = "exana kor", grupo = 2, level = 45, mana = 30, vocacoes = { "druid", "elder druid", "knight", "elite knight" } },
  { nome = "Recovery", palavras = "utura", grupo = 2, level = 50, mana = 75, vocacoes = { "knight", "elite knight", "paladin", "royal paladin" } },
  { nome = "Salvation", palavras = "exura gran san", grupo = 2, level = 60, mana = 210, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Cure Curse", palavras = "exana mort", grupo = 2, level = 80, mana = 40, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Intense Wound Cleansing", palavras = "exura gran ico", grupo = 2, level = 80, mana = 200, vocacoes = { "knight", "elite knight" } },
  { nome = "Spirit Mend", palavras = "exura gran tio", grupo = 2, level = 80, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Intense Recovery", palavras = "utura gran", grupo = 2, level = 100, mana = 165, vocacoes = { "knight", "elite knight", "paladin", "royal paladin" } },
  { nome = "Mass Spirit Mend", palavras = "exura mas nia", grupo = 2, level = 150, mana = 250, vocacoes = { "monk", "exalted monk" } },
  { nome = "Fair Wound Cleansing", palavras = "exura med ico", grupo = 2, level = 300, mana = 90, vocacoes = { "knight", "elite knight" } },
  { nome = "Nature's Embrace", palavras = "exura gran sio", grupo = 2, level = 300, mana = 400, vocacoes = { "druid", "elder druid" } },
  { nome = "Restoration", palavras = "exura max vita", grupo = 2, level = 300, mana = 260, vocacoes = { "druid", "sorcerer", "elder druid", "master sorcerer" } },
  { nome = "Arrow Call", palavras = "exevo infir con", grupo = 3, level = 1, mana = 10, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Light Stone Shower Rune", palavras = "adori infir mas tera", grupo = 3, level = 1, mana = 6, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Lightest Magic Missile", palavras = "adori dis min vis", grupo = 3, level = 1, mana = 5, vocacoes = { "none" } },
  { nome = "Lightest Missile Rune", palavras = "adori infir vis", grupo = 3, level = 1, mana = 6, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Find Person", palavras = "exiva", grupo = 3, level = 8, mana = 20, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "House Door List", palavras = "aleta grav", grupo = 3, level = 8, mana = 0, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "House Guest List", palavras = "aleta sio", grupo = 3, level = 8, mana = 0, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "House Kick", palavras = "alana sio", grupo = 3, level = 8, mana = 0, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "House Subowner List", palavras = "aleta som", grupo = 3, level = 8, mana = 0, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Light", palavras = "utevo lux", grupo = 3, level = 8, mana = 20, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Magic Rope", palavras = "exani tera", grupo = 3, level = 9, mana = 20, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Levitate", palavras = "exani hur", grupo = 3, level = 12, mana = 50, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Conjure Arrow", palavras = "exevo con", grupo = 3, level = 13, mana = 100, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Great Light", palavras = "utevo gran lux", grupo = 3, level = 13, mana = 60, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Cancel Magic Shield", palavras = "exana vita", grupo = 3, level = 14, mana = 50, vocacoes = { "druid", "sorcerer", "elder druid", "master sorcerer" } },
  { nome = "Food", palavras = "exevo pan", grupo = 3, level = 14, mana = 120, vocacoes = { "druid", "elder druid" } },
  { nome = "Haste", palavras = "utani hur", grupo = 3, level = 14, mana = 60, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Magic Shield", palavras = "utamo vita", grupo = 3, level = 14, mana = 50, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Poison Field Rune", palavras = "adevo grav pox", grupo = 3, level = 14, mana = 200, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Cure Poison Rune", palavras = "adana pox", grupo = 3, level = 15, mana = 200, vocacoes = { "druid", "elder druid" } },
  { nome = "Fire Field Rune", palavras = "adevo grav flam", grupo = 3, level = 15, mana = 240, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Intense Healing Rune", palavras = "adura gran", grupo = 3, level = 15, mana = 120, vocacoes = { "druid", "elder druid" } },
  { nome = "Light Magic Missile Rune", palavras = "adori min vis", grupo = 3, level = 15, mana = 120, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Conjure Poisoned Arrow", palavras = "exevo con pox", grupo = 3, level = 16, mana = 130, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Convince Creature Rune", palavras = "adeta sio", grupo = 3, level = 16, mana = 200, vocacoes = { "druid", "elder druid" } },
  { nome = "Conjure Bolt", palavras = "exevo con mort", grupo = 3, level = 17, mana = 140, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Destroy Field Rune", palavras = "adito grav", grupo = 3, level = 17, mana = 120, vocacoes = { "druid", "elder druid", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Energy Field Rune", palavras = "adevo grav vis", grupo = 3, level = 18, mana = 320, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Blank Rune", palavras = "adori blank", grupo = 3, level = 20, mana = 50, vocacoes = { "druid", "paladin", "sorcerer", "elder druid", "royal paladin", "master sorcerer" } },
  { nome = "Challenge", palavras = "exeta res", grupo = 3, level = 20, mana = 30, vocacoes = { "elite knight" } },
  { nome = "Strong Haste", palavras = "utani gran hur", grupo = 3, level = 20, mana = 100, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Virtue of Harmony", palavras = "utori virtu", grupo = 3, level = 20, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Virtue of Justice", palavras = "utito virtu", grupo = 3, level = 20, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Virtue of Sustain", palavras = "utura tio", grupo = 3, level = 20, mana = 210, vocacoes = { "monk", "exalted monk" } },
  { nome = "Disintegrate Rune", palavras = "adito tera", grupo = 3, level = 21, mana = 200, vocacoes = { "druid", "elder druid", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Creature Illusion", palavras = "utevo res ina", grupo = 3, level = 23, mana = 100, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Conjure Sniper Arrow", palavras = "exevo con hur", grupo = 3, level = 24, mana = 160, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Stalagmite Rune", palavras = "adori tera", grupo = 3, level = 24, mana = 350, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Ultimate Healing Rune", palavras = "adura vita", grupo = 3, level = 24, mana = 400, vocacoes = { "druid", "elder druid" } },
  { nome = "Charge", palavras = "utani tempo hur", grupo = 3, level = 25, mana = 100, vocacoes = { "knight", "elite knight" } },
  { nome = "Conjure Explosive Arrow", palavras = "exevo con flam", grupo = 3, level = 25, mana = 290, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Find Fiend", palavras = "exiva moe res", grupo = 3, level = 25, mana = 20, vocacoes = { "druid", "elder druid", "knight", "elite knight", "paladin", "royal paladin", "sorcerer", "master sorcerer", "monk", "exalted monk" } },
  { nome = "Heavy Magic Missile Rune", palavras = "adori vis", grupo = 3, level = 25, mana = 350, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Poison Bomb Rune", palavras = "adevo mas pox", grupo = 3, level = 25, mana = 520, vocacoes = { "druid", "elder druid" } },
  { nome = "Summon Creature", palavras = "utevo res", grupo = 3, level = 25, mana = 0, vocacoes = { "druid", "sorcerer", "elder druid", "master sorcerer" } },
  { nome = "Cancel Invisibility", palavras = "exana ina", grupo = 3, level = 26, mana = 200, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Ultimate Light", palavras = "utevo vis lux", grupo = 3, level = 26, mana = 140, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Animate Dead Rune", palavras = "adana mort", grupo = 3, level = 27, mana = 600, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Chameleon Rune", palavras = "adevo ina", grupo = 3, level = 27, mana = 600, vocacoes = { "druid", "elder druid" } },
  { nome = "Fire Bomb Rune", palavras = "adevo mas flam", grupo = 3, level = 27, mana = 600, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Fireball Rune", palavras = "adori flam", grupo = 3, level = 27, mana = 460, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Holy Missile Rune", palavras = "adori san", grupo = 3, level = 27, mana = 300, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Soulfire Rune", palavras = "adevo res flam", grupo = 3, level = 27, mana = 420, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Wild Growth Rune", palavras = "adevo grav vita", grupo = 3, level = 27, mana = 600, vocacoes = { "druid", "elder druid" } },
  { nome = "Icicle Rune", palavras = "adori frigo", grupo = 3, level = 28, mana = 460, vocacoes = { "druid", "elder druid" } },
  { nome = "Stone Shower Rune", palavras = "adori mas tera", grupo = 3, level = 28, mana = 430, vocacoes = { "druid", "elder druid" } },
  { nome = "Thunderstorm Rune", palavras = "adori mas vis", grupo = 3, level = 28, mana = 430, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Poison Wall Rune", palavras = "adevo mas grav pox", grupo = 3, level = 29, mana = 640, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Avalanche Rune", palavras = "adori mas frigo", grupo = 3, level = 30, mana = 530, vocacoes = { "druid", "elder druid" } },
  { nome = "Great Fireball Rune", palavras = "adori mas flam", grupo = 3, level = 30, mana = 530, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Explosion Rune", palavras = "adevo mas hur", grupo = 3, level = 31, mana = 570, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Enchant Party", palavras = "utori mas sio", grupo = 3, level = 32, mana = 120, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Enlighten Party", palavras = "utevo mas sio", grupo = 3, level = 32, mana = 0, vocacoes = { "monk", "exalted monk" } },
  { nome = "Heal Party", palavras = "utura mas sio", grupo = 3, level = 32, mana = 120, vocacoes = { "druid", "elder druid" } },
  { nome = "Magic Wall Rune", palavras = "adevo grav tera", grupo = 3, level = 32, mana = 750, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Protect Party", palavras = "utamo mas sio", grupo = 3, level = 32, mana = 90, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Train Party", palavras = "utito mas sio", grupo = 3, level = 32, mana = 60, vocacoes = { "knight", "elite knight" } },
  { nome = "Conjure Piercing Bolt", palavras = "exevo con grav", grupo = 3, level = 33, mana = 180, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Fire Wall Rune", palavras = "adevo mas grav flam", grupo = 3, level = 33, mana = 780, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Invisibility", palavras = "utana vid", grupo = 3, level = 35, mana = 440, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Energy Bomb Rune", palavras = "adevo mas vis", grupo = 3, level = 37, mana = 880, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Conjure Wand of Darkness", palavras = "exevo gran mort", grupo = 3, level = 41, mana = 250, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Enchant Staff", palavras = "exeta vis", grupo = 3, level = 41, mana = 80, vocacoes = { "master sorcerer" } },
  { nome = "Energy Wall Rune", palavras = "adevo mas grav vis", grupo = 3, level = 41, mana = 1000, vocacoes = { "druid", "elder druid", "sorcerer", "master sorcerer" } },
  { nome = "Enchant Spear", palavras = "exeta con", grupo = 3, level = 45, mana = 350, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Sudden Death Rune", palavras = "adori gran mort", grupo = 3, level = 45, mana = 985, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Paralyze Rune", palavras = "adana ani", grupo = 3, level = 54, mana = 1400, vocacoes = { "druid", "elder druid" } },
  { nome = "Protector", palavras = "utamo tempo", grupo = 3, level = 55, mana = 200, vocacoes = { "knight", "elite knight" } },
  { nome = "Swift Foot", palavras = "utamo tempo san", grupo = 3, level = 55, mana = 400, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Conjure Power Bolt", palavras = "exevo con vis", grupo = 3, level = 59, mana = 700, vocacoes = { "royal paladin" } },
  { nome = "Blood Rage", palavras = "utito tempo", grupo = 3, level = 60, mana = 290, vocacoes = { "knight", "elite knight" } },
  { nome = "Sharpshooter", palavras = "utito tempo san", grupo = 3, level = 60, mana = 450, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Chivalrous Challenge", palavras = "exeta amp res", grupo = 3, level = 150, mana = 80, vocacoes = { "knight", "elite knight" } },
  { nome = "Conjure Royal Star", palavras = "exevo gran con grav", grupo = 3, level = 150, mana = 1000, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Focus Serenity", palavras = "utamo tio", grupo = 3, level = 150, mana = 500, vocacoes = { "monk", "exalted monk" } },
  { nome = "Mentor Other", palavras = "uteta tio", grupo = 3, level = 150, mana = 110, vocacoes = { "monk", "exalted monk" } },
  { nome = "Balanced Brawl", palavras = "exori mas res", grupo = 3, level = 175, mana = 80, vocacoes = { "monk", "exalted monk" } },
  { nome = "Monk familiar", palavras = "utevo gran res tio", grupo = 3, level = 200, mana = 1500, vocacoes = { "monk", "exalted monk" } },
  { nome = "Summon Druid Familiar", palavras = "utevo gran res dru", grupo = 3, level = 200, mana = 3000, vocacoes = { "druid", "elder druid" } },
  { nome = "Summon Knight Familiar", palavras = "utevo gran res eq", grupo = 3, level = 200, mana = 1000, vocacoes = { "knight", "elite knight" } },
  { nome = "Summon Paladin Familiar", palavras = "utevo gran res sac", grupo = 3, level = 200, mana = 2000, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Summon Sorcerer Familiar", palavras = "utevo gran res ven", grupo = 3, level = 200, mana = 3000, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Divine Dazzle", palavras = "exana amp res", grupo = 3, level = 250, mana = 80, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Expose Weakness", palavras = "exori moe", grupo = 3, level = 275, mana = 400, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Focus Harmony", palavras = "utevo nia", grupo = 3, level = 275, mana = 500, vocacoes = { "monk", "exalted monk" } },
  { nome = "Sap Strength", palavras = "exori kor", grupo = 3, level = 275, mana = 300, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Avatar of Balance", palavras = "uteta res tio", grupo = 3, level = 300, mana = 1200, vocacoes = { "monk", "exalted monk" } },
  { nome = "Avatar of Light", palavras = "uteta res sac", grupo = 3, level = 300, mana = 1500, vocacoes = { "paladin", "royal paladin" } },
  { nome = "Avatar of Nature", palavras = "uteta res dru", grupo = 3, level = 300, mana = 2200, vocacoes = { "druid", "elder druid" } },
  { nome = "Avatar of Steel", palavras = "uteta res eq", grupo = 3, level = 300, mana = 800, vocacoes = { "knight", "elite knight" } },
  { nome = "Avatar of Storm", palavras = "uteta res ven", grupo = 3, level = 300, mana = 2200, vocacoes = { "sorcerer", "master sorcerer" } },
  { nome = "Divine Empowerment", palavras = "utevo grav san", grupo = 3, level = 300, mana = 500, vocacoes = { "paladin", "royal paladin" } },
}
